### PR TITLE
fix: show password toggle when property set (#30)

### LINKED ISSUE #30: auro-input: password toggle (eye icon) does not display in svelte app
## Describe the bug
The eye icon that should display on a password type input field is not visible when the component is rendered in a svelte application. 

## To Reproduce
1. Create svelte app and place an `<auro-input type="password">` on the page (my full component looks like this):
   ```
   <auro-input bind:this={fieldPassword} required="true" type="password" label="Password"></auro-input>
   ```
2. Run app locally
4. Type in the password field

## Expected behavior
Next to the X on the right of the component, an eye icon should be displayed.

## Screenshots
password

## Desktop
 - OS: Windows
 - Browser: Chrome
 - Version: 1.3.2

## Additional context
- As you can see in the screenshot, it looks like something is causing the style of the icon to be `visibility: hidden`. 
- The `X` icon displays correctly.

### PR DESCRIPTION
**Pull request by geoffrich**
# Alaska Airlines Pull Request

This PR makes it so the hide/show password toggle is shown when the `type` property or attribute is set to `"password"`. Previously, this only worked when the `type` attribute was set. This is necessary for frameworks like Svelte, which prefer to set the property when available.

Fixes #30

## Summary:

In order to hide/show the password, we were toggling the element's type property between "password" and "text". Instead, I only set an internal state property `_showPassword` and used that to determine the inner `<input>`'s type attribute. The auro-input's type property remains equal to "password". 

Originally I thought we would need to reflect the property since we were using the attribute for styling, but that didn't end up being necessary. I was able to remove the `:host([type="password'])` selector and rely on the toggle only being added to the DOM when `this.type === 'password'`. 

I verified that this change works in a local Svelte app. The password icon displays and can be toggled as many times as desired.

## Type of change:

Please delete options that are not relevant.

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

File: src/auro-input.js [hunk 1]
```diff
@@ -28,7 +28,7 @@ export default class AuroInput extends BaseInput {
     /**
      * @private Boolean value to determine which password icon to show
      */
-    this.showPassword = false;
+    this._showPassword = false;
```
Comment (blackfalcon) [inline src/auro-input.js:31]: So.... the `_`

This is not really a convention we are using anywhere else.

Comment (jason-capsule42) [reply src/auro-input.js:31]: I don't think we need to make that standard. Old legacy C# conventions don't need to follow us here IMO.

File: src/auro-input.js [hunk 2]
```diff
@@ -69,23 +70,16 @@ export default class AuroInput extends BaseInput {
    * @returns {string} returns string based on type
    */
   handleClickShowPassword() {
-    if (this.type === "password") {
-      this.type = "text";
-      this.showPassword = true;
-      this.focus();
```
Comment (jason-capsule42) [inline src/auro-input.js:75]: I wouldn't say it's within the scope of this bug but it would be nice if the focus cursor position didn't jump to the front of the input.

Comment (blackfalcon) [reply src/auro-input.js:75]: @jason-capsule42 please create a separate issue and drop the link here.

File: src/auro-input.js (hunk 1 above)
Comment (geoffrich) [reply src/auro-input.js:31]: I followed the example in the [Lit docs](https://lit.dev/docs/components/properties/#public-properties-and-internal-state) on internal reactive state a little too closely. I'll remove the underscore.

File: src/auro-input.js (hunk 2 above)
Comment (geoffrich) [reply src/auro-input.js:75]: Oh yeah, that's annoying. Didn't notice it because it doesn't happen on Firefox. Can you open a separate issue for this?

Comment (jason-capsule42) [reply src/auro-input.js:75]: https://github.com/AlaskaAirlines/auro-input/issues/33

**Review by jason-capsule42 — APPROVED** [review]

**Comment by blackfalcon** [comment]
@geoffrich I am assuming that you will follow up with the dev that has this issue in Svelte?
